function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function exportCSV(){const rows=[['날짜','별점','구분','긍정 요소','부정 요소','리뷰 내용','출처 URL'],...state.reviews.map(r=>[r.date,r.rating||'',r.sentiment,r.positive.join(' · '),r.negative.join(' · '),r.body,r.url])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`${filenameSafe(state.businessName)}_고객리뷰_${today()}.csv`)}

async function exportExcel(){
 if(!state.reviews.length){toast('먼저 분석을 실행하세요.','error');return;}if(!window.ExcelJS){toast('엑셀 모듈을 불러오지 못했습니다. 인터넷 연결을 확인하세요.','error');return;}
 $('#excelBtn').disabled=true;$('#excelBtn').innerHTML='<span class="spinner"></span> 엑셀 생성 중';
 try{
  const wb=new ExcelJS.Workbook();wb.creator='Brandbuilder';wb.lastModifiedBy='Brandbuilder';wb.created=new Date();wb.modified=new Date();wb.subject='네이버플레이스 고객리뷰 분석';wb.company='Brandbuilder';
  const C={yellow:'FFFFCC00',yellowSoft:'FFFFF2B3',black:'FF111111',white:'FFFFFFFF',red:'FFD91F37',redSoft:'FFFFE8EC',greenSoft:'FFEAF8F0',gray:'FFF2F2EF',line:'FFD8D8D0'};
  const border={top:{style:'thin',color:{argb:C.line}},left:{style:'thin',color:{argb:C.line}},bottom:{style:'thin',color:{argb:C.line}},right:{style:'thin',color:{argb:C.line}}};
  function title(ws,text,endCol){ws.mergeCells(1,1,1,endCol);const c=ws.getCell(1,1);c.value=text;c.fill={type:'pattern',pattern:'solid',fgColor:{argb:C.black}};c.font={name:'맑은 고딕',size:22,bold:true,color:{argb:C.yellow}};c.alignment={horizontal:'center',vertical:'middle'};ws.getRow(1).height=38;}
  function header(ws,row,start,end){for(let col=start;col<=end;col++){const c=ws.getCell(row,col);c.fill={type:'pattern',pattern:'solid',fgColor:{argb:C.yellow}};c.font={name:'맑은 고딕',bold:true,color:{argb:C.black}};c.alignment={horizontal:'center',vertical:'middle',wrapText:true};c.border=border;}ws.getRow(row).height=28;}
  function bodyStyle(ws,startRow,endRow,endCol){for(let r=startRow;r<=endRow;r++){for(let c=1;c<=endCol;c++){const cell=ws.getCell(r,c);cell.font={name:'맑은 고딕',size:10,color:{argb:C.black}};cell.alignment={vertical:'top',wrapText:true};cell.border=border;}ws.getRow(r).height=34;}}
  function meta(ws,row,label,value,endCol){ws.getCell(row,1).value=label;ws.getCell(row,1).font={bold:true};ws.getCell(row,2).value=value;ws.mergeCells(row,2,row,endCol);ws.getCell(row,2).alignment={wrapText:true};}
  const raw=wb.addWorksheet('고객리뷰',{views:[{state:'frozen',ySplit:4}]});title(raw,`${state.businessName} 고객리뷰 · 제작자 Brandbuilder`,4);meta(raw,2,'수집 리뷰',state.reviews.length,4);meta(raw,3,'수집 기준',`${state.source||'사용자 입력'} · 기준일 ${state.analyzedAt||today()} · ${state.placeUrl||'플레이스 URL 미입력'}`,4);raw.addRow(['날짜','별점','리뷰 내용','출처 URL']);header(raw,4,1,4);state.reviews.forEach(r=>raw.addRow([r.date,r.rating||'',r.body,r.url||state.placeUrl]));bodyStyle(raw,5,raw.rowCount,4);raw.columns=[{width:13},{width:9},{width:70},{width:32}];raw.autoFilter={from:'A4',to:`D${raw.rowCount}`};raw.getColumn(1).numFmt='yyyy-mm-dd';
  const cls=wb.addWorksheet('리뷰분류',{views:[{state:'frozen',ySplit:4}]});title(cls,'리뷰별 긍정·개선 요소 분류',7);cls.mergeCells('A2:G2');cls.getCell('A2').value='명시적 불편·요청이 있을 때만 개선 필요로 분류합니다. 긍정 요소는 노란색, 부정 요소는 빨간색으로 표시합니다. · 제작자 Brandbuilder';cls.getCell('A2').alignment={wrapText:true};cls.getCell('A2').font={color:{argb:C.red}};cls.addRow([]);cls.addRow(['날짜','구분','긍정 요소','부정 요소','개선 제안','리뷰 원문','출처 URL']);header(cls,4,1,7);state.reviews.forEach(r=>cls.addRow([r.date,r.sentiment,r.positive.join(' · '),r.negative.join(' · '),r.improvement,r.body,r.url||state.placeUrl]));bodyStyle(cls,5,cls.rowCount,7);for(let r=5;r<=cls.rowCount;r++){const s=cls.getCell(r,2).value;if(s==='긍정'){cls.getCell(r,3).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.yellowSoft}};}if(s==='부정'||s==='개선동반 긍정'){cls.getCell(r,4).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.redSoft}};cls.getCell(r,4).font={name:'맑은 고딕',size:10,color:{argb:C.red}};}}cls.columns=[{width:13},{width:16},{width:28},{width:25},{width:44},{width:70},{width:30}];cls.autoFilter={from:'A4',to:`G${cls.rowCount}`};
  const imp=wb.addWorksheet('개선과제',{views:[{state:'frozen',ySplit:4}]});title(imp,'부정 요소 기반 개선 과제',6);imp.mergeCells('A2:F2');imp.getCell('A2').value='부정 리뷰를 비난 지표가 아닌 고객의 개선 제안으로 해석했습니다. 같은 리뷰가 여러 주제에 포함될 수 있습니다.';imp.getCell('A2').alignment={wrapText:true};imp.getCell('A2').font={color:{argb:C.red}};imp.addRow([]);imp.addRow(['우선순위','개선 주제','언급 수','대표 고객 신호','실행 제안','권장 점검 지표']);header(imp,4,1,6);if(state.improvements.length)state.improvements.forEach(x=>imp.addRow([x.priority,x.theme,x.count,x.signal,x.action,x.metric]));else imp.addRow(['낮음','명확한 부정 신호 없음',0,'명시적 불편·요청이 확인되지 않음','긍정 자산을 대표 콘텐츠로 강화하고 월 단위로 신호 변화를 관찰','긍정 언급 증가율·재방문 언급률']);bodyStyle(imp,5,imp.rowCount,6);for(let r=5;r<=imp.rowCount;r++){imp.getCell(r,1).font={name:'맑은 고딕',size:10,bold:true,color:{argb:C.red}};imp.getCell(r,2).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.redSoft}};}imp.columns=[{width:12},{width:24},{width:10},{width:55},{width:55},{width:30}];
  const sns=wb.addWorksheet('SNS콘텐츠계획',{views:[{state:'frozen',ySplit:4}]});title(sns,'반복 긍정 요소 기반 SNS 콘텐츠 계획',10);sns.mergeCells('A2:J2');sns.getCell('A2').value='언급 수가 많은 긍정 자산부터 콘텐츠화합니다. 각 주제마다 훅 5안과 작동 이유를 포함합니다.';sns.getCell('A2').alignment={wrapText:true};sns.addRow([]);sns.addRow(['순위','반복 긍정 주제','언급 수','콘텐츠 훅 5안','훅 작동 이유','권장 형식','촬영·구성','CTA','게시 빈도','플레이스 URL']);header(sns,4,1,10);state.snsPlans.forEach(x=>sns.addRow([x.rank,x.theme,x.count,x.hooks.map((h,i)=>`${i+1}. ${h}`).join('\n'),x.reasons.map((h,i)=>`${i+1}. ${h}`).join('\n'),x.format,x.shoot,x.cta,x.frequency,state.placeUrl]));bodyStyle(sns,5,sns.rowCount,10);for(let r=5;r<=sns.rowCount;r++){sns.getCell(r,2).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.yellowSoft}};sns.getRow(r).height=110;}sns.columns=[{width:8},{width:24},{width:10},{width:55},{width:45},{width:20},{width:46},{width:30},{width:14},{width:30}];
  const dash=wb.addWorksheet('요약대시보드');title(dash,'고객리뷰 분석 대시보드',10);const analyzed=state.reviews.filter(r=>r.sentiment!=='분석 제외');const p=analyzed.filter(r=>r.sentiment==='긍정').length;const m=analyzed.filter(r=>r.sentiment==='개선동반 긍정').length;const n=analyzed.filter(r=>r.sentiment==='부정').length;const ratio=analyzed.length?(p+m)/analyzed.length:0;dash.getRow(3).values=['전체 리뷰','긍정 리뷰','','개선 필요 리뷰','긍정 비율','','상호','업종','기준일','제작자'];dash.getRow(4).values=[state.reviews.length,p,'',m+n,ratio,'',state.businessName,state.industry,state.analyzedAt||today(),'Brandbuilder'];header(dash,3,1,10);for(let c=1;c<=10;c++){dash.getCell(4,c).alignment={horizontal:'center',vertical:'middle'};dash.getCell(4,c).font={name:'맑은 고딕',size:c<=5?18:10,bold:true,color:{argb:(c===4&&m+n>0)?C.red:C.black}};dash.getCell(4,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:c===4?C.redSoft:C.yellowSoft}};}dash.getCell('E4').numFmt='0.0%';dash.mergeCells('A6:J6');dash.getCell('A6').value=$('#conclusion').textContent;dash.getCell('A6').fill={type:'pattern',pattern:'solid',fgColor:{argb:C.gray}};dash.getCell('A6').font={name:'맑은 고딕',size:12,bold:true};dash.getCell('A6').alignment={wrapText:true,vertical:'middle'};dash.getRow(6).height=48;dash.getRow(9).values=['반복 긍정 주제','언급 수','','개선 주제','언급 수','','SNS 우선 주제','언급 수','','플레이스 URL'];header(dash,9,1,10);const maxRows=Math.max(state.positiveThemes.length,state.improvements.length,state.snsPlans.length,1);for(let i=0;i<Math.min(maxRows,8);i++){const r=10+i;dash.getCell(r,1).value=state.positiveThemes[i]?.name||'';dash.getCell(r,2).value=state.positiveThemes[i]?.count||'';dash.getCell(r,4).value=state.improvements[i]?.theme||'';dash.getCell(r,5).value=state.improvements[i]?.count||'';dash.getCell(r,7).value=state.snsPlans[i]?.theme||'';dash.getCell(r,8).value=state.snsPlans[i]?.count||'';dash.getCell(r,10).value=i===0?state.placeUrl:'';for(let c=1;c<=10;c++){dash.getCell(r,c).font={name:'맑은 고딕',size:10,color:{argb:c===4?C.red:C.black}};dash.getCell(r,c).alignment={wrapText:true};}}dash.columns=[{width:26},{width:11},{width:3},{width:27},{width:11},{width:3},{width:27},{width:11},{width:3},{width:34}];
  const buffer=await wb.xlsx.writeBuffer();downloadBlob(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`${filenameSafe(state.businessName)}_네이버플레이스_리뷰분석_${today()}.xlsx`);toast('5개 시트 엑셀 리포트를 만들었습니다.','success');
 }catch(e){console.error(e);toast(`엑셀 생성 실패: ${e.message}`,'error');}
 finally{$('#excelBtn').disabled=false;$('#excelBtn').textContent='엑셀 리포트 다운로드';}
}

function initTabs(){$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab).classList.add('active');}));}
async function handleSelectedFile(file){if(!file)return;$('#fileStatus').textContent='읽는 중';try{const arr=await readFile(file);setRawReviews(arr,file.name);toast(`${arr.length}건을 인식했습니다.`,'success');}catch(e){console.error(e);$('#fileStatus').textContent='오류';toast(`파일 읽기 실패: ${e.message}`,'error');}}
function init(){
 initTabs();$('#sampleBtn').addEventListener('click',()=>{setRawReviews(SAMPLE_REVIEWS,'내장 샘플 데이터');if(!$('#businessName').value)$('#businessName').value='샘플 브랜드';toast('샘플 리뷰 12건을 불러왔습니다.','success');});$('#analyzeBtn').addEventListener('click',runAnalysis);$('#resetBtn').addEventListener('click',resetApp);$('#collectBtn').addEventListener('click',collectFromApi);$('#saveBtn').addEventListener('click',saveProject);$('#loadBtn').addEventListener('click',loadProject);$('#excelBtn').addEventListener('click',exportExcel);$('#csvBtn').addEventListener('click',exportCSV);$('#printBtn').addEventListener('click',()=>window.print());$('#reviewSearch').addEventListener('input',renderReviews);$('#sentimentFilter').addEventListener('change',renderReviews);$('#fileInput').addEventListener('change',e=>handleSelectedFile(e.target.files[0]));
 const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>handleSelectedFile(e.dataTransfer.files[0]));
 const savedApi=localStorage.getItem('brandbuilder-review-api')||'';$('#apiEndpoint').value=savedApi;$('#apiEndpoint').addEventListener('change',()=>localStorage.setItem('brandbuilder-review-api',$('#apiEndpoint').value));
}
window.addEventListener('DOMContentLoaded',init);
